# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: raft.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\x12\x04raft\"O\n\x12ReplicatedLogEntry\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\x12\x0b\n\x03key\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\t\x12\x0c\n\x04term\x18\x04 \x01(\x04\"z\n\x14\x41ppendEntriesRequest\x12\x14\n\x0cprevlogindex\x18\x01 \x01(\x04\x12)\n\x07\x65ntries\x18\x02 \x03(\x0b\x32\x18.raft.ReplicatedLogEntry\x12\x13\n\x0b\x63ommitindex\x18\x03 \x01(\x04\x12\x0c\n\x04term\x18\x04 \x01(\x04\"3\n\x12\x41ppendEntriesReply\x12\x0c\n\x04term\x18\x01 \x01(\x04\x12\x0f\n\x07success\x18\x02 \x01(\x08\x32O\n\x04Raft\x12G\n\rAppendEntries\x12\x1a.raft.AppendEntriesRequest\x1a\x18.raft.AppendEntriesReply\"\x00\x42*\n\x15io.grpc.examples.raftB\tRaftProtoP\x01\xa2\x02\x03HLWb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\025io.grpc.examples.raftB\tRaftProtoP\001\242\002\003HLW'
  _REPLICATEDLOGENTRY._serialized_start=20
  _REPLICATEDLOGENTRY._serialized_end=99
  _APPENDENTRIESREQUEST._serialized_start=101
  _APPENDENTRIESREQUEST._serialized_end=223
  _APPENDENTRIESREPLY._serialized_start=225
  _APPENDENTRIESREPLY._serialized_end=276
  _RAFT._serialized_start=278
  _RAFT._serialized_end=357
# @@protoc_insertion_point(module_scope)
